### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by hermannsblum** [alanfischer/hassiq#12]
Is HTTPS supported for the connection? I get 404 even tough password and url are working in the browser.

**Comment by hermannsblum** [comment]
Hi! Thanks for the offer, but my hass is configured to only connect via local wifi
Is there any debug interface I where I could find out what‘s the connection problem?

**Comment by alanfischer** [comment]
Are you running this from an actual Garmin device, or just in the simulator?    If its on a device, is your phone connected to your local wifi?

**Comment by hermannsblum** [comment]
running in the vivoactive 3 when the phone is in the local wifi

**Comment by alanfischer** [comment]
Are you connecting by ip? What url do you have in the host field?  You could also try by disabling cell data on your phone as an experiment and see if that makes it work, forcing it to use the lan connection.  I admit I have not experimented much with a local only Hass instance.

**Comment by hermannsblum** [comment]
Just to let you know that I have not forgotten this: I will try to debug the network requests coming into my hassio to see what is the request incoming and response outgoing and where this issue is rooted.

**Comment by Voz-DeCarabas** [comment]
Love the idea of this. I’m using a forerunner 235
Can you confirm the account that the password should be for? I’m getting 401 errors and then the following in the log on Home Assistant
Login attempt or request with invalid authentication from 192.168.1.95
8:24 PM components/http/ban.py (WARNING)
You need to use a bearer token to access /api/states/group.all_switches from 192.168.1.95
8:24 PM components/http/auth.py (WARNING)

**Comment by alanfischer** [comment]
The latest version of HassIQ has been uploaded to the connect iq store, and now supports the updated Home Assistant authorization method.

**Comment by hermannsblum** [comment]
Just as a documentation in case anybody get's the same problems:
You cannot connect with the garmin watch to a server that uses a self-signed certificate. Therefore, you cannot connect to local instances like `https://hassio.local/`.

Using a reverse proxy like the hass.io nginx addon you can enable both https and http connections and then connect from the watch using http.

Works like a charm now, Thanks for this app :)
