### ISSUE TITLE
Connection Not Authorized

### ISSUE THREAD

**Issue by Andreln** [alanfischer/hassiq#13]
Hi. I recently found your app, but I'm having trouble using it. 

I get the status:401.

Not sure what I've done wrong. I've entered both the IP to the homeassistant website and my password on the widget. I am able to log in to the website through the mobile browser.

Home Assistant message
`Login attempt or request with invalid authentication from 192.168.0.102`

**Comment by alanfischer** [comment]
Do you have legacy password support enabled in home assistant?

**Comment by theoneandonlyjoshua** [comment]
I have legacy API enabled and am facing same issue. Status:0 then Status :404

**Comment by alanfischer** [comment]
@theoneandonlyjoshua Do you have a valid group set in the hassiq settings?  Is your hass instance available from your phone at the same address you have in the settings?

**Comment by Andreln** [comment]
@alanfischer My configuration was missing the auth_providers part, but after adding that the watch now displays the 404 instead.

I haven't made any groups, but I tried to switch to `group.all_switches` , but that doesn't work either.

At the moment I don't really have the need for groups. Is it necessary to define a custom group?

**Comment by alanfischer** [comment]
@Andreln Specifying a group is to avoid sending too many entities to the widget at once, there is an unfortunately small connect iq memory limit on some devices, so limiting it to only the ones you would trigger from you device is helpful.

To debug, I would probably make a HA group with just a few entities in it, and try to set that as your group in hassiq, see if you have any luck

**Comment by Andreln** [comment]
@alanfischer It works perfectly when I created a new group. Thank you for the help. Greatly appreciate it.
