### ISSUE TITLE
Connection issue - Vivoactive 3

### ISSUE THREAD

**Issue by biochemguy** [alanfischer/hassiq#25]
Hi, 
This great widget used to work with my watch for over a year, but it stopped working (unsure when, but probably over 1 month ago). I could not trigger anything, so I reinstalled the widget and it now cannot connect to homeassistant. It goes to status:-300. 

I tried creating a new long lived access token and change the group of devices to be controlled. I can access homeassistant with my phone using the url in the widget. I tried entering the url with and without the http:// prefix.

I am running the latest homeassistant version (99.0)  with HassIQ version 1.09

Unsure what is the exact problem.

**Comment by alanfischer** [comment]
I believe the issue is Connect IQ no longer supports non https urls, so you would need to get your home assistant setup behind https, not http.

There is a thread here covering similar issues. https://forums.garmin.com/developer/connect-iq/i/bug-reports/connect-version-4-20-broke-local-http-access

**Comment by biochemguy** [comment]
Thanks for the reply. I did not know that. It makes sense, as my home assistant is http. I will look into changing it to https.
