### ISSUE TITLE
Triggering all enities in a group at once

### ISSUE THREAD

**Issue by DotNet2Web** [alanfischer/hassiq#38]
Hi Alan,

First of all thanks for this great widget!!! just found out about it and already working with it.

The thing I have is, in my living room I got several lights that I only want to turn on and off at once. No need to do this light per light.

Is there a way to trigger all entities in a selected group? 

If not, is it possible to add code for it or to tell me were to find the triggering code then I can make a fix myself and contribute to this amazing project!

`GarminLights:
  entities: 
    - group.LightsLivingRoom
    - group.LightsKitchen`

LightsLivingRoom contains 8 lights, LightsKitchen contains 6 lights.

**Comment by luke-barnett** [comment]
Probably just as good for you to create a light group which will give you a single light entity to work with.

**Comment by superm1** [comment]
Maybe if you add a scene that changes them how you want that you activate?

I personally do something like this without hassiq. When my TV state changes to "playing" I activate a tv watching scene.
