### ISSUE TITLE
Status: -400 Error

### ISSUE THREAD

**Issue by miles246** [alanfischer/hassiq#44]
Hi, I hope you are fine. I installed the HassIQ app on my vivoactive3 watch, after entering the local IP address with http, and entered the Access Token, the watch showed the status -400. On the first try, the Garmin app asked me for a username and password but this time it didn't. What should I do? Thanks.

**Comment by alanfischer** [comment]
I would suggest going through this thread:

https://community.home-assistant.io/t/home-assistant-interface-for-garmins-connect-iq-platform/16882/174

There are various reasons why you may be seeing the error.
