### ISSUE TITLE
Venu 2 plus / Fenix 7 support

### ISSUE THREAD

**Issue by O-Palda** [alanfischer/hassiq#46]
Hello Alan,
could you please update the app to support newest watches? 
Thank you very much and kind regards

**Comment by yannlet** [comment]
Hi Alan,

Exactly the same issue. Hardware of venu 2 plus is the same as venu 2, so I think it "just" needs to be enabled. Thank you in advance !

**Comment by jspanitz** [comment]
Just came here to open a issue - glad to see someone beat me to it

**Comment by Veldkornet** [comment]
Along with the Fenix 7, the Epix Gen2 please :)

**Comment by vdelab** [comment]
Hello, I second that, for the fenix 7...
Question : isn't it sufficient to update the manifest.xml file and add the related productid ? Since SW and HW should be compatible...
I have done this, but for those more literate with github and compiler....

**Comment by jspanitz** [comment]
> Hello, I second that, for the fenix 7... Question : isn't it sufficient to update the manifest.xml file and add the related productid ? Since SW and HW should be compatible... I have done this, but for those more literate with github and compiler....

Was wondering this myself - I'd fork the project and add the values if I had them - haven't looked for them tbh - if someone has them handy, post them here plz

**Comment by jspanitz** [comment]
>  haven't looked for them tbh - if someone has them handy, post them here plz

Found them:
<iq:product id="fenix7"/>
<iq:product id="fenix7s"/>
<iq:product id="fenix7x"/>

**Comment by jspanitz** [comment]
Added pull request for Fenix 7 - if someone else fines the venu 2 plus product ids and posts them here, I can initiate the update for them as well

**Comment by Veldkornet** [comment]
You can find them [here](https://developer.garmin.com/connect-iq/reference-guides/devices-reference):
```
<iq:product id="fenix7"/>
<iq:product id="fenix7s"/>
<iq:product id="fenix7x"/>
<iq:product id="epix2"/>
<iq:product id="venu2plus"/>
```

**Comment by vdelab** [comment]
Hello, values are quite easy.
I found them on other projects...
fenix7
fenix7s
fenix7x

Keep us posted...

**Comment by jspanitz** [comment]
Thanks for the other device types and info on where to find them.  I updated my fork and submitted the pull request.  Hopefully @alanfischer is still maintaining and will update :)

**Comment by alanfischer** [comment]
Updated
