### ISSUE TITLE
Feature Request - Sensor/Person Display

### ISSUE THREAD

**Issue by sibero80** [alanfischer/hassiq#9]
Writing from Colombia to thank you for this great APP.
I'm still getting the hangs of monkey C, havent been able to pull my first app, but getting there slowly.

Do you think it could be possible to add sensors/device states to the Display group so when the widget pulls the data from the server, it could concatenate the sensor/device state next to the name of the item?  something like $SENSOR/DEVICE - $VALUE

Thank you again.

EDIT:
After reviewing your commit history I noticed this feature is already implemented.
However when I add a device/person/group/sensor, the STATE does not show.
I'm on the latest HASS.IO.
Should I be setting up something else in my group so this works ok?
Thank you!

**Comment by alanfischer** [comment]
Thanks for the report!  I will try to get a fix in this week to properly show the state for all objects with states.

**Comment by alanfischer** [comment]
I added a minor change that should show states of any entities that are known.  https://github.com/alanfischer/hassiq/pull/11

Once I get a new build of the app pushed to the CIQ store I can update this issue.

**Comment by sibero80** [comment]
Thank you!

**Comment by alanfischer** [comment]
The latest version of the CIQ app should support showing states.
